name = "Nix"
grammar = "nix"
path_suffixes = ["nix"]
brackets = [
    { start = "${", end = "}", close = false, newline = false },
    { start = "{", end = "}", close = false, newline = false },
    { start = "[", end = "]", close = false, newline = false },
    { start = "(", end = ")", close = false, newline = false },
    { start = "<", end = ">", close = false, newline = false },
]
autoclose_before = ";:.,=}])>` \n\t\""
line_comments = ["# "]
